apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa # name of the HPA
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-app # name of the deployment to scale
  minReplicas: 3
  maxReplicas: 7
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization # target type
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization # target type
          averageUtilization: 50
