# Ingress-nginx Helm Chart Values
# This file contains all configuration for ingress-nginx controller
# Optimized for Minikube with limited resources

# Controller configuration
controller:
  # Service configuration
  service:
    type: NodePort
    nodePorts:
      http: 30080 # Access via http://localhost:30080 or minikube-ip:30080
      https: 30443 # Access via https://localhost:30443 or minikube-ip:30443

  # Resource limits for Minikube
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
    limits:
      cpu: 200m
      memory: 256Mi

  # Replica count (1 for development/test)
  replicaCount: 1

  # Additional configuration for better performance in Minikube
  config:
    # Enable gzip compression
    use-gzip: "true"
    # Increase proxy timeouts
    proxy-connect-timeout: "15"
    proxy-send-timeout: "600"
    proxy-read-timeout: "600"
    # Enable CORS for development
    enable-cors: "true"

  # Metrics and monitoring (optional - disable to save resources)
  metrics:
    enabled: false

  # Admission webhooks (can be disabled in development)
  admissionWebhooks:
    enabled: true
    failurePolicy: Fail
    port: 8443
    certificate: "/usr/local/certificates/cert"
    key: "/usr/local/certificates/key"
    namespaceSelector: {}
    objectSelector: {}

# Default backend (optional - lightweight 404 page)
defaultBackend:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 20m
      memory: 40Mi

# RBAC configuration
rbac:
  create: true
  scope: false

# Service account
serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: true

# Pod Security Context
podSecurityContext:
  runAsUser: 101
  runAsGroup: 82
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Security Context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 82
  capabilities:
    drop:
      - ALL
    add:
      - NET_BIND_SERVICE

# Namespace configuration
namespaceOverride: "ingress-nginx"
