apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: simple-kafka
  namespace: kafka
  annotations:
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      # Message size settings for large files
      message.max.bytes: 52428800           # 50MB
      replica.fetch.max.bytes: 52428800     
      fetch.max.bytes: 52428800             
      socket.request.max.bytes: 52428800    
      auto.create.topics.enable: true
    storage:
      type: ephemeral
    resources:
      requests:
        memory: 512Mi
        cpu: "300m"
      limits:
        memory: 1Gi
        cpu: "500m"
    jvmOptions:
      -Xms: 256m
      -Xmx: 512m
  # No Zookeeper section for KRaft mode
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 128Mi
          cpu: "100m"
        limits:
          memory: 256Mi
          cpu: "200m"
